### PR TITLE
Add new app icon

### LINKED ISSUE #16: Create app icon
I'm thinking of something similar to the official Yale Dining app, but with a different font since the official YaleNew font is only licensed for official University-endorsed activities, and a plus sign somewhere.

### PR DESCRIPTION
**Pull request by ErikBoesen**
Open to feedback on the design of this.

Fixes #16

### CODE REVIEW

**Comment by ErikBoesen** [comment]
Ah yes, this is already an adaptive icon but there's no foreground and background separation.

**Comment by ErikBoesen** [comment]
Fixed!

**Comment by amalik12** [comment]
I don't really like the plus sign inside of the D. Was the original design unable to fit?

**Comment by ErikBoesen** [comment]
@amalik12 I realized that previously the + was just barely crossing the edge of the circular icons' content area so I just moved it inside. I'll move it back out and try fitting it in the bottom right corner as previously.

**Comment by ErikBoesen** [comment]
Hmmm, actually, do you think maybe we should omit the Y? Since the app is just called Dining Plus?

**Comment by amalik12** [comment]
> 
> 
> @amalik12 I realized that previously the + was just barely crossing the edge of the circular icons' content area so I just moved it inside. I'll move it back out and try fitting it in the bottom right corner as previously.

You can resize the icon to fit the content area using the slider in the asset importer:
image

**Comment by amalik12** [comment]
> 
> 
> Hmmm, actually, do you think maybe we should omit the Y? Since the app is just called Dining Plus?

I'm fine either way.

**Comment by ErikBoesen** [comment]
How's this?

**Comment by amalik12** [comment]
Looks good!

**Comment by ErikBoesen** [comment]
Thanks for the edit access! I can keep making pull requests so that you can review (I'm not _nearly_ as experienced as you with Android development, so this may be best), but I know you're quite busy so I'm happy to just directly commit and not pester you. Do you have a preference?

**Comment by amalik12** [comment]
I think it'll be fine if you keep making pull requests. I'll be able to review them when necessary.

**Comment by ErikBoesen** [comment]
Great, will do!

**Pull request merged**
